---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull isharani21/spe_miniproject:latest
      
    - name: running container
      shell: docker run -it -d isharani21/spe_miniproject:latest
